image: docker:latest
  
variables:
    SONAR_TOKEN: "f188d828b4ee5666618d2c045ff7855bf395b600"
    SONAR_HOST_URL: "http://sonny.titaniumsystem.es/sonar"
    GIT_DEPTH: 0

services:
  - docker:dind

stages:
  - build_job
  - sonar_job

build:
  image: gradle:5.0-jdk8-alpine
  stage: build_job
  script:
    - gradle build
  artifacts:
    paths:
       - api_citame_empresas/gradle/wrapper/*.jar
       
sonar:
  image: gradle:alpine
  stage: sonar_job
  script: gradle sonarqube -Dsonar.qualitygate.wait=true
  allow_failure: true
